name: CI

on: [push, pull_request]

jobs:
  sca_sast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run npm audit
      run: npm audit --audit-level=moderate

    - name: Run audit-ci
      run: npx audit-ci --config audit-ci.json

    - name: Run ESLint
      run: npx eslint .

    - name: Set up Snyk
      uses: snyk/actions/setup@master

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      run: snyk test

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config p/ci
